export const imageLabels = {
  'hero-fab':'클린룸의 웨이퍼와 정밀 반도체 제조 장비',
  'silicon-wafer':'실리콘 잉곳과 회로가 형성된 웨이퍼, 분리된 다이',
  'transistor':'트랜지스터 소자와 반도체 회로의 확대 장면',
  'computing':'프로세서와 메모리 부품이 배치된 컴퓨터 회로',
  'lithography':'웨이퍼 스테이지와 노광 장비의 정밀 광학부',
  'process-chamber':'웨이퍼를 가공하는 진공 공정 챔버 내부',
  'advanced-packaging':'로직 칩과 메모리 칩을 함께 배치한 패키지',
  'ecosystem':'반도체 제조 시설과 지원 시설이 연결된 캠퍼스',
  'concept-semiconductor':'실리콘 결정과 작은 반도체 칩',
  'concept-conductors':'구리 도체, 세라믹 절연체, 실리콘 반도체 재료',
  'concept-silicon':'고순도 실리콘 조각과 가공된 단결정',
  'concept-mosfet':'세 개의 단자가 있는 전력용 MOSFET 패키지',
  'concept-cpu':'중앙처리장치 패키지와 금속 열 분산판',
  'concept-gpu':'프로세서와 메모리를 배치한 GPU 가속기 기판',
  'concept-dram':'메모리 칩과 금색 접점이 있는 DRAM 모듈',
  'concept-nand':'NAND 플래시와 제어기가 배치된 NVMe SSD 기판',
  'concept-oxidation':'웨이퍼 보트가 들어 있는 석영관 열산화 장비',
  'concept-euv-duv':'노광 장비에 쓰이는 정밀 광학 미러 조립체',
  'concept-etching':'웨이퍼 척과 상부 가스 공급부가 있는 식각 챔버',
  'concept-cvd':'가스 공급 샤워헤드와 기판을 갖춘 CVD 증착 장비',
  'concept-ald':'얇게 코팅된 웨이퍼와 정밀 가스 공급 장치',
  'concept-ion-implantation':'진공 빔라인과 웨이퍼 처리부가 있는 이온주입 장비',
  'concept-cmp':'연마 패드와 웨이퍼 캐리어가 있는 CMP 장비',
  'concept-cleaning':'세정 장비 안에서 순수로 씻는 웨이퍼',
  'concept-tsv':'실리콘 층을 관통하는 구리 연결부의 개념 표현',
  'concept-interposer':'로직과 메모리 사이를 연결하는 인터포저의 개념 표현',
  'concept-hbm':'로직 칩 옆에 적층한 메모리 다이의 개념 표현',
  'concept-integration':'칩을 나란히 놓는 방식과 위로 쌓는 방식의 개념 표현',
  'concept-fabless':'칩의 회로 배치를 설계하는 반도체 설계 작업실',
  'concept-foundry':'제조 장비와 웨이퍼 이송 장치가 있는 클린룸',
  'process-overview':'유리창 너머로 보이는 반도체 공정 설비',
  'packaging-overview':'칩을 정밀하게 배치하는 패키징 장비'
};
