export const industryHub = {
  title: '설계에서 시스템까지, 역할로 읽는 반도체 산업',
  description: '회사 이름을 외우기보다 “누가 무엇을 맡고, 다음 역할과 어떻게 연결되는가”를 먼저 이해하는 산업 생태계 지도입니다.',
  note: '아래 흐름은 초보 학습을 위한 역할 중심 단순화입니다. 실제 산업에서는 기업 간 계약·공급 관계가 병렬로 얽혀 있고, 한 기업이 설계·제조·패키징 등 여러 역할을 동시에 수행하기도 합니다.',
  stages: [
    {
      number: '01',
      id: 'eda-ip',
      label: 'EDA / IP',
      en: 'Design Foundation',
      question: '어떻게 설계할까?',
      role: '회로를 설계·검증하는 도구와 재사용 가능한 설계 자산을 제공합니다.',
      tone: 'foundation',
      status: 'MVP 2.0',
    },
    {
      number: '02',
      id: 'fabless',
      label: 'Fabless',
      en: 'Chip Design',
      question: '무엇을 만들까?',
      role: '제품 요구사항을 반도체 아키텍처와 회로 설계로 바꿉니다.',
      tone: 'design',
      concept: 'fabless',
    },
    {
      number: '03',
      id: 'foundry',
      label: 'Foundry',
      en: 'Wafer Manufacturing',
      question: '어떻게 만들까?',
      role: '설계 데이터를 공정 기술과 생산 설비를 이용해 실제 웨이퍼 위 회로로 구현합니다.',
      tone: 'manufacture',
      concept: 'foundry',
    },
    {
      number: '04',
      id: 'equipment-materials',
      label: 'Equipment / Materials',
      en: 'Manufacturing Support',
      question: '무엇으로 만들까?',
      role: '노광·식각·증착·검사 장비와 웨이퍼·가스·케미컬·포토레지스트 등 생산 기반을 공급합니다.',
      tone: 'support',
      support: true,
      status: 'MVP 2.0',
    },
    {
      number: '05',
      id: 'osat-packaging',
      label: 'OSAT / Packaging',
      en: 'Assembly & Test',
      question: '어떻게 연결하고 검증할까?',
      role: '웨이퍼에서 나온 다이를 전기적으로 연결·보호하고, 테스트를 통해 출하 가능한 칩으로 완성합니다.',
      tone: 'packaging',
      concept: 'packaging',
    },
    {
      number: '06',
      id: 'system',
      label: 'System',
      en: 'Product & Service',
      question: '어디에 쓰일까?',
      role: '칩을 메모리·센서·소프트웨어와 결합해 스마트폰·자동차·데이터센터 같은 실제 시스템에 적용합니다.',
      tone: 'system',
      status: 'MVP 2.0',
    },
  ],
  learningPath: [
    {
      number: 28,
      id: 'ecosystem',
      label: '산업 생태계',
      description: '전체 역할과 연결 구조를 먼저 이해합니다.',
    },
    {
      number: 29,
      id: 'fabless',
      label: 'Fabless',
      description: '칩을 직접 생산하지 않고 설계에 집중하는 역할을 배웁니다.',
    },
    {
      number: 30,
      id: 'foundry',
      label: 'Foundry',
      description: '설계 데이터를 실제 웨이퍼 공정으로 구현하는 역할을 배웁니다.',
    },
  ],
  principles: [
    {
      en: 'ROLE FIRST',
      title: '기업명보다 역할',
      description: '처음에는 회사 이름보다 “설계·제조·패키징·시스템 중 어떤 문제를 해결하는가?”를 기준으로 산업을 봅니다.',
    },
    {
      en: 'INTERDEPENDENCE',
      title: '혼자 만드는 칩은 없다',
      description: '설계가 좋아도 제조·장비·소재·패키징이 연결되지 않으면 제품이 완성되지 않습니다. 공급망은 역할 간 의존 구조입니다.',
    },
    {
      en: 'SUPPORT LAYER',
      title: '장비·소재는 한 단계가 아니라 지원망',
      description: '장비·소재 기업은 Foundry 뒤에만 존재하는 단계가 아니라 제조와 패키징의 여러 공정에 걸쳐 기술과 생산 기반을 제공합니다.',
    },
  ],
};
