export const processHub = {
  title: '웨이퍼에서 패키징 직전까지',
  description: '12~22번 개념을 공정의 역할과 학습 순서로 연결한 MVP 제조공정 지도입니다.',
  note: '실제 반도체 제조에서는 아래 공정을 한 번씩 직선으로 수행하지 않습니다. 제품과 층의 목적에 따라 증착·노광·식각·세정·CMP 등이 반복되고, 사이사이에 계측·검사가 들어갑니다.',
  concepts: [
    { num: 12, id: 'fabrication', label: '전체 공정', en: 'Fabrication', role: '큰 그림', tone: 'overview' },
    { num: 13, id: 'oxidation', label: '산화', en: 'Oxidation', role: '표면에 산화막 형성', tone: 'film' },
    { num: 14, id: 'lithography', label: '노광', en: 'Lithography', role: '회로 패턴 정의', tone: 'pattern' },
    { num: 15, id: 'euv-duv', label: 'DUV / EUV', en: 'Exposure', role: '빛으로 미세 패턴 전사', tone: 'pattern' },
    { num: 16, id: 'etching', label: '식각', en: 'Etching', role: '선택적으로 재료 제거', tone: 'shape' },
    { num: 17, id: 'deposition', label: '증착', en: 'Deposition', role: '필요한 막을 형성', tone: 'film' },
    { num: 18, id: 'cvd', label: 'CVD', en: 'CVD', role: '기상 반응으로 막 형성', tone: 'film' },
    { num: 19, id: 'ald', label: 'ALD', en: 'ALD', role: '원자층 단위 정밀 증착', tone: 'film' },
    { num: 20, id: 'ion-implantation', label: '이온주입', en: 'Ion Implant', role: '전기적 성질 조절', tone: 'property' },
    { num: 21, id: 'cmp', label: 'CMP', en: 'Planarization', role: '표면 평탄화', tone: 'finish' },
    { num: 22, id: 'cleaning', label: '세정', en: 'Cleaning', role: '오염과 잔여물 제거', tone: 'finish' },
  ],
  families: [
    {
      id: 'foundation',
      number: '01',
      title: '기판과 표면 준비',
      description: '웨이퍼의 표면 상태를 준비하고 필요한 절연막을 형성합니다.',
      concepts: ['fabrication', 'oxidation'],
    },
    {
      id: 'pattern',
      number: '02',
      title: '패턴을 정의',
      description: '포토레지스트와 빛을 이용해 어디를 가공할지 정합니다.',
      concepts: ['lithography', 'euv-duv'],
    },
    {
      id: 'build',
      number: '03',
      title: '깎고 쌓아 구조 형성',
      description: '식각과 증착을 반복하며 회로의 실제 형상을 만듭니다.',
      concepts: ['etching', 'deposition', 'cvd', 'ald'],
    },
    {
      id: 'electrical',
      number: '04',
      title: '전기적 성질 조절',
      description: '이온주입으로 필요한 영역의 전기적 특성을 바꿉니다.',
      concepts: ['ion-implantation'],
    },
    {
      id: 'finish',
      number: '05',
      title: '평탄화와 세정',
      description: '다음 층을 만들 수 있도록 표면 높이와 청정도를 다시 준비합니다.',
      concepts: ['cmp', 'cleaning'],
    },
  ],
  principles: [
    {
      title: '반복',
      en: 'REPEAT',
      description: '한 층을 만든 뒤 끝나는 것이 아니라, 필요한 회로 층을 만들기 위해 여러 공정이 반복됩니다.',
    },
    {
      title: '선택성',
      en: 'SELECTIVITY',
      description: '필요한 곳만 만들고 제거해야 하므로 재료·마스크·공정 조건의 선택성이 중요합니다.',
    },
    {
      title: '검증',
      en: 'MEASURE',
      description: '각 단계 사이에는 계측과 검사가 들어가 두께·형상·결함·정렬 상태를 확인합니다.',
    },
  ],
};
