export const sourceCatalog = {
  asml_basics: ['ASML · The basics of microchips', 'https://www.asml.com/en/technology/all-about-microchips/microchip-basics', '공식 기술자료'],
  samsung_semiconductor: ['Samsung Semiconductor · 반도체', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-semiconductor/', '공식 용어집'],
  openstax_resistivity: ['OpenStax · Resistivity and Resistance', 'https://openstax.org/books/university-physics-volume-2/pages/9-3-resistivity-and-resistance', '대학 교육자료'],
  openstax_band: ['OpenStax · Band Theory of Solids', 'https://openstax.org/books/university-physics-volume-3/pages/9-5-band-theory-of-solids', '대학 교육자료'],
  samsung_wafer: ['Samsung Semiconductor · 웨이퍼', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-wafer/', '공식 용어집'],
  samsung_ingot: ['Samsung Semiconductor · 잉곳', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-ingot/', '공식 용어집'],
  intel_transistor: ['Intel · The Transistor, Explained', 'https://newsroom.intel.com/tech101/the-transistor-explained', '공식 기술자료'],
  samsung_transistor: ['Samsung Semiconductor · 트랜지스터', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-transistor/', '공식 용어집'],
  ieee_mosfet: ['IEEE Technology Navigator · MOSFET / MIS Structures', 'https://technav.ieee.org/topic/metal-insulator-structures/', '학술 기술자료'],
  samsung_cmos: ['Samsung Semiconductor · CMOS', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-cmos/', '공식 용어집'],
  intel_cpu_gpu: ['Intel · CPU vs. GPU', 'https://www.intel.com/content/www/us/en/products/docs/processors/cpu-vs-gpu.html', '공식 기술자료'],
  nvidia_gpu: ['NVIDIA · GPU 용어 설명', 'https://www.nvidia.com/content/Control-Panel-Help/vLatest/ko-kr/mergedProjects/nvcplKOR/glossary.htm', '공식 용어집'],
  samsung_soc: ['Samsung Semiconductor · SoC (System on Chip)', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-soc/', '공식 용어집'],
  samsung_dram: ['Samsung Semiconductor · D램', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-dram/', '공식 용어집'],
  micron_dram: ['Micron · How DRAM changed the world', 'https://www.micron.com/about/blog/memory/dram/how-dram-changed-the-world', '공식 기술자료'],
  samsung_nand: ['Samsung Semiconductor · NAND Flash Memory', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-nand-flash-memory/', '공식 용어집'],
  micron_nand: ['Micron · 40 years of flash memory innovation', 'https://www.micron.com/about/blog/memory/nand/flash-forward-celebrating-40-years-of-memory-innovation', '공식 기술자료'],
  asml_process: ['ASML · How microchips are made', 'https://www.asml.com/en/technology/all-about-microchips/how-microchips-are-made', '공식 기술자료'],
  applied_products: ['Applied Materials · Semiconductor Products & Process Map', 'https://www.appliedmaterials.com/us/en/semiconductor/products.html', '공식 기술자료'],
  samsung_oxide: ['Samsung Semiconductor · 산화막', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-oxide-layer/', '공식 용어집'],
  samsung_lithography: ['Samsung Semiconductor · 노광', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-photolithography/', '공식 용어집'],
  asml_light: ['ASML · Lithography light & lasers', 'https://www.asml.com/en/technology/lithography-principles/light-and-lasers', '공식 기술자료'],
  applied_etch: ['Applied Materials · Etch', 'https://www.appliedmaterials.com/us/en/semiconductor/products/processes/etch.html', '공식 기술자료'],
  lam_glossary: ['Lam Research · Technical Glossary', 'https://www.lamresearch.com/technical-glossary/', '공식 기술자료'],
  applied_create: ['Applied Materials · Materials Deposition', 'https://www.appliedmaterials.com/us/en/semiconductor/products/create.html', '공식 기술자료'],
  applied_ion: ['Applied Materials · VIISta Trident Ion Implant', 'https://www.appliedmaterials.com/us/en/product-library/viista-trident.html', '공식 기술자료'],
  applied_ion_blog: ['Applied Materials · Ion Implantation Technology', 'https://www.appliedmaterials.com/us/en/newsroom/blogs/implant-innovation-enables-the-compound-semiconductor-roadmap.html', '공식 기술자료'],
  applied_cmp: ['Applied Materials · Materials Removal & CMP', 'https://www.appliedmaterials.com/us/en/semiconductor/products/shape.html', '공식 기술자료'],
  applied_cmp_blog: ['Applied Materials · The Role of CMP in Device Scaling', 'https://www.appliedmaterials.com/us/en/blog/blog-posts/the-role-of-cmp-in-device-scaling.html', '공식 기술자료'],
  samsung_cleaning: ['Samsung Semiconductor · 세정공정', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/zero-residue-zero-contaminants-semiconductor-cleaning/', '공식 기술자료'],
  applied_cleaning: ['Applied Materials · Advanced Wafer Cleaning Technologies', 'https://www.appliedmaterials.com/us/en/newsroom/press-releases/052626-applied-materials-partners-screen-adv-wafer-cleaning-tech-to-epic-center.html', '공식 산업자료'],
  samsung_packaging: ['Samsung Semiconductor · 패키징', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-packaging/', '공식 용어집'],
  intel_packaging: ['Intel · Advanced Packaging', 'https://newsroom.intel.com/manufacturing/intel-leads-the-way-with-advanced-packaging', '공식 기술자료'],
  semi_packaging: ['SEMI · 반도체 패키징 기술교육', 'https://www.semi.org/ko/connect/events/packaging-tutorial-2024', '산업 교육자료'],
  samsung_tsv: ['Samsung Semiconductor · TSV (Through Silicon Via)', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/semiconductor-glossary-tsv/', '공식 용어집'],
  samsung_hbm: ['Samsung Semiconductor · HBM', 'https://semiconductor.samsung.com/kr/dram/hbm/', '공식 기술자료'],
  jedec_memory: ['JEDEC · Main Memory Standards (DDR SDRAM, HBM)', 'https://www.jedec.org/', '산업 표준'],
  applied_hbm: ['Applied Materials · HBM & Advanced Packaging Bottlenecks', 'https://www.appliedmaterials.com/us/en/newsroom/blogs/tackling-key-hbm-and-advanced-packaging-bottlenecks-for-ai-era.html', '공식 기술자료'],
  tsmc_cowos: ['TSMC 3DFabric · CoWoS®', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm', '공식 기술자료'],
  samsung_adv_pkg: ['Samsung Foundry · Advanced Heterogeneous Integration', 'https://semiconductor.samsung.com/foundry/advanced-package/advanced-heterogeneous-integration/', '공식 기술자료'],
  tsmc_hpc: ['TSMC · HPC Platform / 2.5D & 3D Integration', 'https://www.tsmc.com/english/dedicatedFoundry/technology/platform_HPC_tech_WLSI', '공식 기술자료'],
  semi_valuechain: ['SEMI · Semiconductor Value Chain Map', 'https://discover.semi.org/rs/320-QBB-055/images/SCC-Scope3-Category1-GHG-Guidelines-2024-FINAL.pdf', '산업 협회자료'],
  tsmc_oip: ['TSMC · Open Innovation Platform®', 'https://www.cld.tsmc.com/english/dedicatedFoundry/oip', '공식 생태계자료'],
  samsung_glossary: ['Samsung Semiconductor · 반도체 용어 모음', 'https://semiconductor.samsung.com/kr/support/tools-resources/dictionary/just-the-essentials-semiconductor-terminologyzip/', '공식 용어집'],
  tsmc_foundry: ['TSMC · Dedicated IC Foundry', 'https://www.tsmc.com/english/dedicatedFoundry', '공식 산업자료'],
  tsmc_grand: ['TSMC · Grand Alliance', 'https://www.tsmc.com/english/dedicatedFoundry/grandAlliance', '공식 생태계자료'],
};

export const referencesByConcept = {
  semiconductor: ['samsung_semiconductor', 'asml_basics', 'openstax_band'],
  conductors: ['openstax_resistivity', 'openstax_band', 'samsung_semiconductor'],
  silicon: ['asml_basics', 'samsung_ingot', 'samsung_semiconductor'],
  wafer: ['samsung_wafer', 'samsung_ingot', 'asml_basics'],
  transistor: ['intel_transistor', 'samsung_transistor', 'samsung_cmos'],
  mosfet: ['intel_transistor', 'ieee_mosfet', 'samsung_cmos'],
  'logic-memory': ['asml_basics', 'samsung_soc', 'samsung_dram'],
  cpu: ['intel_cpu_gpu', 'samsung_soc'],
  gpu: ['intel_cpu_gpu', 'nvidia_gpu'],
  dram: ['samsung_dram', 'micron_dram'],
  nand: ['samsung_nand', 'micron_nand'],
  fabrication: ['asml_process', 'applied_products'],
  oxidation: ['samsung_oxide', 'intel_transistor', 'asml_process'],
  lithography: ['samsung_lithography', 'asml_process', 'asml_light'],
  'euv-duv': ['asml_light', 'asml_process'],
  etching: ['applied_etch', 'lam_glossary', 'asml_process'],
  deposition: ['applied_create', 'lam_glossary', 'asml_process'],
  cvd: ['applied_create', 'lam_glossary'],
  ald: ['applied_create', 'lam_glossary'],
  'ion-implantation': ['applied_ion', 'applied_ion_blog'],
  cmp: ['applied_cmp', 'applied_cmp_blog'],
  cleaning: ['samsung_cleaning', 'applied_cleaning', 'asml_process'],
  packaging: ['samsung_packaging', 'intel_packaging', 'semi_packaging'],
  tsv: ['samsung_tsv', 'applied_hbm', 'tsmc_cowos'],
  interposer: ['tsmc_cowos', 'samsung_adv_pkg', 'tsmc_hpc'],
  hbm: ['samsung_hbm', 'jedec_memory', 'applied_hbm'],
  integration: ['samsung_adv_pkg', 'tsmc_hpc', 'intel_packaging', 'semi_packaging'],
  ecosystem: ['semi_valuechain', 'tsmc_grand', 'tsmc_oip'],
  fabless: ['samsung_glossary', 'semi_valuechain', 'tsmc_oip'],
  foundry: ['tsmc_foundry', 'semi_valuechain', 'tsmc_oip'],
};
