export const visualGuides = [
  {
    id: 'foundations',
    number: '01',
    eyebrow: 'FOUNDATIONS',
    title: '실리콘에서 칩까지',
    description: '반도체가 재료에서 회로가 되기까지 가장 기본적인 네 단계를 연결합니다.',
    note: '실제 칩은 훨씬 많은 재료와 공정을 사용하지만, 처음에는 “재료 → 판 → 소자 → 칩”의 흐름을 잡는 것이 중요합니다.',
    type: 'flow',
    nodes: [
      { label: 'Silicon', sub: '전기적 성질을 조절하는 재료', concept: 'silicon' },
      { label: 'Wafer', sub: '회로를 함께 만드는 얇은 판', concept: 'wafer' },
      { label: 'Transistor', sub: '전류를 제어하는 작은 스위치', concept: 'transistor' },
      { label: 'Chip', sub: '많은 소자와 배선의 집합', concept: 'semiconductor' },
    ],
    related: ['silicon', 'wafer', 'transistor', 'semiconductor'],
  },
  {
    id: 'computing',
    number: '02',
    eyebrow: 'COMPUTING & MEMORY',
    title: '계산하는 칩과 기억하는 칩',
    description: 'CPU·GPU가 계산하고 DRAM·NAND가 데이터를 보관하는 역할 차이를 한눈에 봅니다.',
    note: 'CPU와 GPU는 처리 방식이 다르고, DRAM과 NAND는 저장 목적이 다릅니다. 실제 시스템에서는 네 역할이 함께 연결됩니다.',
    type: 'computing',
    nodes: [
      { label: 'CPU', sub: '범용 명령과 제어', concept: 'cpu', lane: 'compute' },
      { label: 'GPU', sub: '대규모 병렬 계산', concept: 'gpu', lane: 'compute' },
      { label: 'DRAM', sub: '작업 중 데이터를 빠르게 공급', concept: 'dram', lane: 'memory' },
      { label: 'NAND', sub: '전원이 꺼져도 데이터를 보관', concept: 'nand', lane: 'memory' },
    ],
    related: ['logic-memory', 'cpu', 'gpu', 'dram', 'nand'],
  },
  {
    id: 'process',
    number: '03',
    eyebrow: 'MANUFACTURING',
    title: '웨이퍼에서 회로를 만드는 공정 지도',
    description: '산화·노광·식각·증착·이온주입·CMP·세정이 어떻게 반복되는지 이해합니다.',
    note: '아래는 학습을 위한 대표 흐름입니다. 실제 제조에서는 목적에 따라 각 단계가 여러 번 반복되고 계측·검사가 사이에 들어갑니다.',
    type: 'process',
    nodes: [
      { label: 'Wafer', concept: 'wafer' },
      { label: 'Oxidation', concept: 'oxidation' },
      { label: 'Lithography', concept: 'lithography' },
      { label: 'DUV / EUV', concept: 'euv-duv' },
      { label: 'Etching', concept: 'etching' },
      { label: 'Deposition', concept: 'deposition' },
      { label: 'CVD / ALD', concept: 'cvd' },
      { label: 'Ion Implant', concept: 'ion-implantation' },
      { label: 'CMP', concept: 'cmp' },
      { label: 'Cleaning', concept: 'cleaning' },
      { label: 'Packaging', concept: 'packaging' },
    ],
    related: ['fabrication', 'lithography', 'etching', 'deposition', 'cmp', 'cleaning'],
  },
  {
    id: 'hbm',
    number: '04',
    eyebrow: 'ADVANCED PACKAGING',
    title: 'GPU 옆 HBM은 어떻게 연결될까?',
    description: '여러 DRAM 다이, TSV, 인터포저와 GPU가 한 패키지에서 데이터를 주고받는 구조를 단순화했습니다.',
    note: '제품마다 베이스 다이와 패키지 구조가 다를 수 있습니다. 여기서는 HBM을 이해하는 데 필요한 핵심 연결 관계만 보여줍니다.',
    type: 'hbm',
    nodes: [
      { label: 'DRAM Stack', sub: '여러 DRAM 다이를 수직 적층', concept: 'dram' },
      { label: 'TSV', sub: '다이를 위아래로 연결', concept: 'tsv' },
      { label: 'HBM', sub: '넓은 I/O로 높은 대역폭 확보', concept: 'hbm' },
      { label: 'Interposer', sub: 'HBM과 GPU 사이의 넓은 연결', concept: 'interposer' },
      { label: 'GPU', sub: '많은 데이터를 병렬 처리', concept: 'gpu' },
    ],
    related: ['dram', 'tsv', 'interposer', 'hbm', 'integration', 'gpu'],
  },
  {
    id: 'industry',
    number: '05',
    eyebrow: 'SEMICONDUCTOR ECOSYSTEM',
    title: '하나의 칩을 만드는 산업 생태계',
    description: '설계 도구에서 칩 설계·제조·패키징·완제품까지 역할 중심으로 공급망을 봅니다.',
    note: '한 기업이 여러 역할을 맡을 수 있으며 장비·소재 기업은 제조와 패키징의 여러 단계에 걸쳐 참여합니다.',
    type: 'industry',
    nodes: [
      { label: 'EDA / IP', sub: '설계 도구와 재사용 설계 자산' },
      { label: 'Fabless', sub: '제품과 회로를 설계', concept: 'fabless' },
      { label: 'Foundry', sub: '웨이퍼에 회로를 제조', concept: 'foundry' },
      { label: 'Equipment / Materials', sub: '공정 장비와 소재를 공급', support: true },
      { label: 'OSAT / Packaging', sub: '연결·보호·테스트', concept: 'packaging' },
      { label: 'System', sub: '칩을 제품과 서비스에 적용' },
    ],
    related: ['ecosystem', 'fabless', 'foundry', 'packaging'],
  },
];

export const visualGuideById = Object.fromEntries(visualGuides.map((guide) => [guide.id, guide]));
